# DS 3000 HW 1

## Due: Friday Sept. 12 @ 11:59 PM EST

**Extra Credit Deadline: Wednesday Sept. 10th @ 11:59 PM**

Name: 

### Submission Instructions
Submit this `ipynb` file to Gradescope (this can also be done via the assignment on Canvas).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to gradescope.

### Tips for success
- Start early
- Make use of Piazza (also accessible through Canvas)
- Make use of Office Hours
- Remember to use cells and headings to make the notebook easy to read (if a grader cannot find the answer to a problem, you will receive no points for it)
- Under no circumstances may one student view or share their ungraded homework or quiz with another student [(see also)](http://www.northeastern.edu/osccr/academic-integrity), though you are welcome to **talk about** (*not* show each other your answers to) the problems.

# Part 1: Lists and Flow and Functions, Oh my!
## Part 1.1: Manual Data Entry (25 points)


How would you manually track temperature changes throughout the day without an automated weather station? Go to this website: [this website](https://www.weather.gov/) and look up your local area's current temperature. You are going to write a function that takes manual input of temperature readings (entered by you), stores all readings in a list, stops once you enter 15 values or four consecutive increasing values (whichever comes first), and returns the temperature data.
For this problem:

- Call your function `temp_tracker`
- Make sure that you use the `input()` option within your function to accept entries
- Make sure you are saving all entries in a list
- Use `if-else` and a `while` loop
- When you have written the function, call:

`temperature_log = temp_tracker()`

`temperature_log`

and manually check the weather website to enter the current temperature (refresh the page every few minutes for updates).

**Note**: There may be multiple ways to get this function to work, but to receive full points, your function **must** have the five components listed above (there may be more efficient ways to do it, but I want you to show me you know how to use *these methods*).

In [1]:
def last_4_are_increasing(temps):
    """
    Check if the last four temperatures in the list are strictly increasing.
    
    Args:
        temps (list of float): List of recorded temperatures.
    Returns:
        bool: True if the last four temperatures are strictly increasing, False otherwise.
    """
    if len(temps) < 4:
        return False
    else:
        return temps[-1] > temps[-2] > temps[-3] > temps[-4]
    
def temp_tracker():
    """
    Continuously prompt the user to enter temperatures until either 15 temperatures or last 4 are increaing.
    Returns:
        list of float: List of recorded temperatures.
    """
    inputs = []
    while len(inputs) < 15 and not last_4_are_increasing(inputs):
        temp = float(input("Enter a temperature: "))
        inputs.append(temp)
    
    return inputs

temperature_log = temp_tracker()
temperature_log

[1.0, 2.0, 3.0, 4.0]

# Part 2: Numpy
## Part 2.1: Creating Arrays (5 points)

Create the following two arrays using the NumPy library. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}10 & 2 & -1 & -24\\
-.1 & 22 & -6 & 3\\
-4 & 2 & -3 & 3.2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}10 & 1 & -4\\
4 & -6 & -1\\
1.2 & -4 & -12\\
3.2 & -2 & -1\\
3 & -4 & -42
\end{bmatrix}$$

Then, uncomment out the code provided to print them and verify they are correct.

In [2]:
# make sure to import numpy library
import numpy as np

In [3]:
array_a = np.array([[10, 2, -1, -24],
                    [-0.1, 22, -6, 3],
                    [-4, 2, -3, 3.2]])

array_b = np.array([[10, 1, -4],
                    [4, -6, -1],
                    [1.2, -4, -12],
                    [3.2, -2, -1],
                    [3, -4, -42]])

In [4]:
# uncomment below to print array_a
array_a

array([[ 10. ,   2. ,  -1. , -24. ],
       [ -0.1,  22. ,  -6. ,   3. ],
       [ -4. ,   2. ,  -3. ,   3.2]])

In [5]:
# uncomment below to print array_b
array_b

array([[ 10. ,   1. ,  -4. ],
       [  4. ,  -6. ,  -1. ],
       [  1.2,  -4. , -12. ],
       [  3.2,  -2. ,  -1. ],
       [  3. ,  -4. , -42. ]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b`, explain what happended in a markdown cell. Then remove the last column of `t_array_b` and try to add them again. What is the result? In a markdown cell explain why the addition worked

In [6]:
# 1
print("Shape:", array_a.shape, "Size:", array_a.size, "nd:", array_a.ndim, "nbytes:", array_a.nbytes)
print("Shape:", array_b.shape, "Size:", array_b.size, "nd:", array_b.ndim, "nbytes:", array_b.nbytes)

# 2
t_array_a = array_a.T
t_array_b = array_b.T

# 3 
# print(array_a + t_array_b)


t_array_b = t_array_b[:, :-1]
array_a + t_array_b


Shape: (3, 4) Size: 12 nd: 2 nbytes: 96
Shape: (5, 3) Size: 15 nd: 2 nbytes: 120


array([[ 20. ,   6. ,   0.2, -20.8],
       [  0.9,  16. , -10. ,   1. ],
       [ -8. ,   1. , -15. ,   2.2]])

The addition did not work because the shapes of the two arrays were not compatible for addition. Array_a has a shape of (3, 4) and t_array_b has a shape of (3, 5). For two arrays to be added together, they must have the same shape or be broadcastable to a common shape. In this case, the number of columns in array_a (4) does not match the number of columns in t_array_b (5), so the addition operation cannot be performed.

The second method works because after removing the last column of t_array_b, its shape becomes (3, 4), which matches the shape of array_a (3, 4). Now that both arrays have the same shape, they can be added together element-wise.

# Part 3: Pandas Pokémon
## Part 3.1: Reading in Data (5 points)

On Canvas is the `pokedata.csv` file. Read this data set in, using the `Pokedex` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [7]:
# make sure to import pandas library
import pandas as pd

In [8]:
pokedex = pd.read_csv('pokedata.csv', index_col='Pokedex')
pokedex.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense  
Pokedex                   
1            49       49  
2            62       63  
3            82       83  
4            52       43  
5            64       58

## Part 3.2: Manipulating Data (20 points)

1. Add a new column to the data set that calculates the BMI of the Pokémon. The formula for BMI using Imperial Units (such as these data contain) is = $703 \times \frac{Weight}{Height^2}$. Print the first few rows.
    2. Use indexing and the `.idxmax()` and `.idxmin()` functions to find the Pokémon that have (a) the highest BMI and (b) the lowest BMI.
1. Create a subset of the Pokémon Data that you created in (1) which (a) includes only Pokémon that have `Defense >= 62` and (b) **excludes** all Pokémon with the Water `MainType`. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the **full** Pokémon Data from the data from (1). Create a markdown cell and explain:
    2. What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [9]:
# 1
pokedex['BMI'] = 703 * pokedex['Weight'] / (pokedex['Height'] ** 2)
print(pokedex.head())

# 2
max_bmi = pokedex['BMI'].idxmax()
min_bmi = pokedex['BMI'].idxmin()
print("Max:", pokedex.loc[max_bmi, "Pokemon"])
print("Min:", pokedex.loc[min_bmi, "Pokemon"])

# 3
no_water_high_defense = pokedex[(pokedex['Defense'] >= 62) & (pokedex['MainType'] != 'Water')]
print(no_water_high_defense.head())

# 4
pokedex.describe()

            Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense        BMI  
Pokedex                              
1            49       49  30.756250  
2            62       63  13.265023  
3            82       83  24.837606  
4            52       43  22.823090  
5            64       58  15.930611  
Max: Golem
Min: Haunter
           Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                       

Height       Weight      Damage   BaseSpeed      Attack  \
count  151.000000   151.000000  151.000000  151.000000  151.000000   
mean    46.894040   100.766954   64.218543   68.933775   72.913907   
std     37.880717   131.299070   28.585519   26.746880   26.755421   
min      8.000000     0.200000   10.000000   15.000000    5.000000   
25%     28.000000    21.800000   45.000000   46.500000   51.000000   
50%     39.000000    66.100000   60.000000   70.000000   70.000000   
75%     59.000000   124.250000   80.000000   90.000000   92.000000   
max    346.000000  1014.100000  250.000000  140.000000  134.000000   

          Defense         BMI  
count  151.000000  151.000000  
mean    68.225166   32.764506  
std     26.916704   23.189403  
min      5.000000    0.035425  
25%     50.000000   20.856877  
50%     65.000000   30.042735  
75%     84.000000   38.245600  
max    180.000000  153.707174

The .describe() function ran on the numerical Series in the DataFrame, such as Height, Weight, Attack, Defense, and Speed. It did not run on the categorical Series like Name, MainType, and SubType. The difference is that the .describe() function provides summary statistics (like count, mean, std, min, max, and quartiles) for numerical data, which are meaningful for quantitative analysis. For categorical data, these statistics do not apply.

# Part 4: Numpy and Pandas Together

## Part 4.1: Reading the Data (5 points)

For this task, using `seaborn`, you need to import the  `tips` dataset. Print the first few rows of the dataset and describe the dataset using `describe()`

In [10]:
import pandas as pd
import seaborn as sns

In [11]:
tips = sns.load_dataset('tips')

print(tips.head())
print(tips.describe())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000


# Part 4.2: Manipulating dataset (25 points)

1. Extract the `total_bill` column as a NumPy array. Slice the array to get elements from index 10 to 20 (inclusive). Print the sliced array.

2. Using `iloc`, select rows 5-15 (inclusive) and columns 1-3 (inclusive), and display the result. Using `loc`, select all rows where `time` is `Dinner` and display only the `total_bill` and `tip` columns.

3. Create a new column called `tip_percentage` that calculates the tip as a percentage of the total bill. Display the new columns after calculation

4. Create a new DataFrame with a single column called `bill_category` that categorizes each bill as `Low` (< \$15), `Medium` (\$15-
\$25), or `High` (> \$25). Use pd.concat to add this new column to the original dataset. Save the modified dataset to a CSV file named `modified_tips.csv`. Print the head of the `modified_tips.csv`


In [ ]:
# 1
total_bill_array = tips['total_bill'].to_numpy()
print(total_bill_array[10:21])

# 2
print(tips.iloc[5:16, 1:4])

dinner_tips = tips.loc[tips['time'] == 'Dinner', ['total_bill', 'tip']]
print(dinner_tips)

# 3
tips['tip_percentage'] = round((tips['tip'] / tips['total_bill']) * 100, 2)
print("tip_percentage column:")
print(tips['tip_percentage'].head())

# 4
def categorize_bill(bill):
    """
    Categorize the bill amount into 'Low', 'Medium', or 'High'.
    Args:
        bill (float): The total bill amount.
    Returns:
        str: 'Low' if bill < 15, 'Medium' if 15 <= bill <= 25, 'High' if bill > 25.
    """
    if bill < 15:
        return 'Low'
    elif 15 <= bill <= 25:
        return 'Medium'
    else:
        return 'High'

# Create bill_category column
bill_category_df = pd.DataFrame({'bill_category': tips['total_bill'].apply(categorize_bill)})

# Concat and Save
tips = pd.concat([tips, bill_category_df], axis=1)
tips.to_csv('modified_tips.csv', index=False) 

# Read and Display
modified_tips = pd.read_csv('modified_tips.csv')
modified_tips.head()

[10.27 35.26 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92]
     tip     sex smoker
5   4.71    Male     No
6   2.00    Male     No
7   3.12    Male     No
8   1.96    Male     No
9   3.23    Male     No
10  1.71    Male     No
11  5.00  Female     No
12  1.57    Male     No
13  3.00    Male     No
14  3.02  Female     No
15  3.92    Male     No
     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[176 rows x 2 columns]
tip_percentage column:
0     5.94
1    16.05
2    16.66
3    13.98
4    14.68
Name: tip_percentage, dtype: float64


total_bill   tip     sex smoker  day    time  size  tip_percentage  \
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94   
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05   
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66   
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98   
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68   

  bill_category  
0        Medium  
1           Low  
2        Medium  
3        Medium  
4        Medium