# DS3000 Day 0
## Class Introduction
September 4/5, 2025

Content:
- Motivating Clear Communication in DS
- Admin/Syllabus Review
- Data Collection/Getting to Know You
- Python Basics (only some)
- Multiple **extra credit**
- Numpy

Note: **Some of you are new to Python, please review ``Pre-Course Notebook`` by this weekend. Ask the TAs or me if you have questions**
    
### Assignment Due Dates:
* Getting to Know You (Sept. 12 via Gradescope)
* Homework 1 (Sept. 12 via Gradescope)

## Functions in a bit more detail

In the pre-course notebook (or DS 2000/2500), you should have seen:

* defining and calling functions
* functions with multiple inputs
* functions with multiple outputs (tuple unpacking to the rescue!)


# Time for a Group Activity. 

![me](https://media.makeameme.org/created/extra-credit-give.jpg)


## Write a function called apply_discount that takes a dictionary of items (where keys are item names and values are prices) and a discount percentage. The function should:

- Print each item and its original price
- Apply the discount to all items
- Return a new dictionary with discounted prices
- Make sure you put a docstring for the function


In [16]:
def apply_discount(items, discount_percent):
    """ applies discount to the prices of the items from the shopping_cart dictionary
    
    Args:
        items (dict): dictionary of the shopping list
        discounted_percent (val): the percentage to apply
        
    Return:
        discounted_items (dict): dictionary of discounted prices
    """ 
    discounted_items = {}
    for key, its in items.items():
        its=its-(its*0.2)
        discounted_items[key]=its

    return discounted_items
        
       
        

# Test your function
shopping_cart = {
    "laptop": 999.99,
    "mouse": 29.99,
    "keyboard": 79.99,
    "monitor": 299.99,
    "headphones": 149.99
}

discounted_items = apply_discount(shopping_cart, 20)  # 20% discount
print("\nDiscounted prices:", discounted_items)


Discounted prices: {'laptop': 799.992, 'mouse': 23.991999999999997, 'keyboard': 63.992, 'monitor': 239.99200000000002, 'headphones': 119.992}


# <span style="color:Red">Let's take a breather</span>
# Individual Extra Credit Task 

## Create code for the following questions and run the cells. If there are errors you need to discuss in the markdown cell why a particular cell did not work. Before submitting delete all the other cells!

Using the Iris dataset do the following questions: 

a) Print the shape

b) Get every 10th row starting from the end using negative step: iris_array[-1::-10]

c) Extract a 2D slice: rows from -20 to -10, columns -4 to -2

d) Create a 1D slice by selecting row -50 and try to transpose it

e) Create a 2D slice with shape (1, 4) from row -50 and transpose it

f) Access positions [:,-5]. Explain the output

In [1]:
import seaborn as sns
import numpy as np

iris = sns.load_dataset('iris')
iris_array = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].to_numpy()

In [2]:
#a 
iris_array.shape

(150, 4)

In [3]:
#b
iris_array[-1::-10]

array([[5.9, 3. , 5.1, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [6. , 2.2, 5. , 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.8, 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.6, 2.5, 3.9, 1.1],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 3.3, 1.4, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
#c
iris_array[-20:-10,-4:-2]

array([[7.4, 2.8],
       [7.9, 3.8],
       [6.4, 2.8],
       [6.3, 2.8],
       [6.1, 2.6],
       [7.7, 3. ],
       [6.3, 3.4],
       [6.4, 3.1],
       [6. , 3. ],
       [6.9, 3.1]])

In [5]:
#d
a=iris_array[-50]
a.T

array([6.3, 3.3, 6. , 2.5])

In [21]:
#e
a=iris_array[-50]
a.T

# OR

a=iris_array[-50:-49]
a.T

# I am considering both as correct as the question was wrongly framed and i saw multiple variations

array([[6.3],
       [3.3],
       [6. ],
       [2.5]])

In [7]:
#f
iris_array[:,-5]

# Since there are only 4 coloumns, we are trying to get the position -1 which does not exist

IndexError: index -5 is out of bounds for axis 1 with size 4