# DS3000 Day 2

Jan 13, 2025

Admin
- New modules for today and next week:
    - `pip install requests plotly matplotlib`
- Homework 1 due this Thur, Jan 16 by end of the day
    - Submit by Tuesday night to get 5\% extra credit.

Push-Up Tracker
- Section 04: 2

Content
- numpy
- pandas
    - series
    - dataframe
- introduce APIs


## Super useful slice syntax on arrays:
(so useful it deserves its own title)

In [ ]:
# by default, the slice indexing chooses start:stop to give the entire object
x = np.array([1, 2, 3])
x[:]

array([1, 2, 3])

In [ ]:
# we can use this to get an entire rows or columns as needed
import numpy as np
x = np.arange(20).reshape((4, 5))
print(x)
print(x[3:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]]


In [ ]:
# get the first column
x[:, 0]

array([ 0,  5, 10, 15])

In [ ]:
x[:, -3:-1]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])


<img src="https://media.tenor.com/9VuG1d2QOOQAAAAM/oh-my-god-its-happening.gif" width=300 />



### Computing stats on an array
- `.sum()`
- `.min()`
- `.max()`
- `.mean()`
- `.std()`
    - standard deviation
- `.var()`
    - variance
- `.argmin()`
    - index of item which is smallest
- `.argmax()`
    - index of item which is largest

In [ ]:
x = np.array([4, 3, 5, 4])
x

array([4, 3, 5, 4])

In [ ]:
# get index of smallest item
# (smallest item, 3, is at index 1)
x.argmin()

1

In [ ]:
y = np.arange(100, 112).reshape((3, 4))
y

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [ ]:
y.sum(), y.min(), y.max(), y.mean(), y.std(), y.var()

(1266, 100, 111, 105.5, 3.452052529534663, 11.916666666666666)

In [ ]:
# axis: which of the shape parameters should I operate on?
# shape = (shape0, shape1)

# axis=0 averages across different rows to give the column average
y.mean(axis=0)

array([104., 105., 106., 107.])

In [ ]:
# axis=1 averages across different columns to give the row average
y.mean(axis=1)

array([101.5, 105.5, 109.5])

**So in a nutshell, when we say axis=0, we mean get stuff from the coloumns and axis =1, to get stuff from rows!**

In [ ]:
# axis is an accepted keyword of all methods listed above
y.min(axis=1)

array([100, 104, 108])

In [ ]:
y.min(axis=0)

array([100, 101, 102, 103])

## Why are we doing this again?

<img src="https://imgur.com/orZWHly.png" width=300 />

In [ ]:
import seaborn as sns

# data source='https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv'
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

## Array Operations:
- array and a scalar:
    - apply operation to every element of array
- array and array:
    - apply operation to corresponding elements of arrays (requires shape or [special](https://numpy.org/doc/stable/user/basics.broadcasting.html) structure)


In [ ]:
y1 = np.arange(12).reshape((3, 4))
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y1 + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
y1 * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [ ]:
y1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# array and array arithmetic
y2 = np.arange(100, 112).reshape((3, 4))
y2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [ ]:
# array and array arithmetic applies operation to corresponding items in arrays
y1 + y2

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122]])

In [ ]:
y1 * y2

array([[   0,  101,  204,  309],
       [ 416,  525,  636,  749],
       [ 864,  981, 1100, 1221]])

In [ ]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# (++) adding a constant row (x) to all rows of a matrix (y1)
# more details here: https://numpy.org/doc/stable/user/basics.broadcasting.html
x = np.array([1000, 2000, 3000, 4000])
y1 + x

array([[1000, 2001, 3002, 4003],
       [1004, 2005, 3006, 4007],
       [1008, 2009, 3010, 4011]])

# Pandas


*   My nickname is Panda (Look at my cute picture)

<img src="https://images.ctfassets.net/rt5zmd3ipxai/25pHfG94sGlRALOqbRvSxl/9f591d8263607fdf923b962cbfcde2a9/NVA-panda.jpg" width=700 />


Pandas is a python module which stores data.  

### If we already have `np.array()`, why do we need pandas?
- pandas supports non numeric data (strings for categorical data, for example)
- pandas supports reading / storing data from more formats
    - csv (spreadsheets)
- pandas more elegantly deals with missing data
- pandas handles indexing woes

You could do almost everything pandas does with numpy arrays ... but it would be much more difficult to accomplish.

### Pandas has two essential objects:
- **dataframe**
    - 2 dimensional data structure
    - you've already seen one today!  (we replicate below)
- **series (vectors)**
    - 1 dimensional data structure, each item associated with some index
    - you could store the weight of all the penguins as a series
        - (all samples of one feature)
    - you could store the weight, bill size, sex, island, etc for a single penguin as a series
        - (all features for one sample)

In [ ]:
import seaborn as sns

# df stands for dataframe.  df_penguin is a dataframe of penguin data
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [ ]:
# the table above is a dataframe
type(df_penguin)

pandas.core.frame.DataFrame

## Pandas Series
### building:
- building: default index
- building: custom index
- building: from a dict

In [ ]:
# each row, or column is a series object
# this represents first row of dataframe
penguin0_series = df_penguin.iloc[0, :]
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
Name: 0, dtype: object

Pandas series contain a sequence of labelled data elements:
- penguin0's `species` is `Adelie`
- penguin0's `island` is `Torgersen`
- penguin0's `bill_length_mm` is `39.1` ...
- penguin0's `<index-name>` is `<corresponding-value>`

A series is quite similar to a dictionary ...

In [ ]:
penguin0_dict = {'species': 'Adelie',
 'island': 'Torgersen',
 'bill_length_mm': 39.1,
 'bill_depth_mm': 18.7,
 'flipper_length_mm': 181.0,
 'body_mass_g': 3750.0,
 'sex': 'Male'}

In [ ]:
import pandas as pd

# build a series from dict
penguin0_series = pd.Series(penguin0_dict)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [ ]:
# you can also pass two corresponding lists / tuples
index = ['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex']
values = ['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male']

penguin0_series = pd.Series(values, index=index)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [ ]:
# sometimes your data has no meaningful index
# pandas will default to indexing things with integers
ice_cream_flavors = 'vanilla', 'chocolate', 'cherry garcia', 'oatmeal'
pd.Series(ice_cream_flavors)

0          vanilla
1        chocolate
2    cherry garcia
3          oatmeal
dtype: object

In [ ]:
# you can access values via .values
penguin0_series.values

array(['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male'],
      dtype=object)

In [ ]:
# you can access index via .index
penguin0_series.index

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

### Using Series (hey, don't they look a little like dictionaries?)
- casting dictionaries to series
- accessing custom index:
    - by name: `series.loc[name]`
    - by position: `series.iloc[idx]`
- iterating: keys, items, iteritems (much like dict)
- deleting an entry

## There are two ways using iloc and loc:

- loc gets rows (and/or columns) with particular labels.
- iloc gets rows (and/or columns) at integer locations.

s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2])

49    a

48    b

47    c

0     d

1     e

2     f

s.loc[0]    # value at index label 0
'd'

s.iloc[0]   # value at index location 0
'a'

s.loc[0:1]  # rows at index labels between 0 and 1 (inclusive)
0    d
1    e

s.iloc[0:1] # rows at index location between 0 and 1 (exclusive)
49    a


In [ ]:
dict_fav_num = {'mohit':  17, 'qi': 7, 'lynne': 3, 'tamrat': 1}
series_fav_num = pd.Series(dict_fav_num)
series_fav_num

mohit     17
qi         7
lynne      3
tamrat     1
dtype: int64

In [ ]:
# lookup value associated with index='eric'
series_fav_num['mohit']

np.int64(17)

In [ ]:
# another way to lookup value associated with index='eric'
series_fav_num.loc['mohit']

np.int64(17)

In [ ]:
# return the value in position 2 (the third position, from top)
series_fav_num.iloc[1]

7

In [ ]:
# each of these access methods can also set the value
series_fav_num.iloc[2] = 1000
series_fav_num

eric        17
qi           7
lynne     1000
tamrat       1
dtype: int64

In [ ]:
for idx in series_fav_num.index:
    print(idx)

eric
qi
lynne
tamrat


In [ ]:
# check membership of item in index
'mohit' in series_fav_num.index

True

In [ ]:
'alice' in series_fav_num.index

False

In [ ]:
# iterating through values
for val in series_fav_num.values:
    print(val)

7
3
1


In [ ]:
# iterating through index (just a like dict!)
# .keys() produces same thing as .index
for key in series_fav_num.keys():
    print(key)

qi
lynne
tamrat


In [ ]:
# iterating through index, value pairs (just like dict!)
for key, val in series_fav_num.items():
    print(key, val)

qi 7
lynne 3
tamrat 1


In [ ]:
# removing a pair by its corresponding index (just like dict!)
del series_fav_num['mohit']

In [ ]:
series_fav_num

qi        7
lynne     3
tamrat    1
dtype: int64

### Describing a `pd.Series`

Just like numpy arrays:
- `Series.argmin()`
    - which index has smallest value
    - pandas gives the row number, not the index
- `Series.argmax()`
    - which index has largest value
    - pandas gives the row number, not the index
- `Series.mean()`
- `Series.min()`
- `Series.max()`
- `Series.std()`
- `Series.var()`

New to pandas:
- `Series.count()`
    - number of item pairs in series
- `Series.describe()`
    - summary statistics

In [ ]:
# number of entries (rows)
series_fav_num.count()

3

# why do things indiviually, when we can just use the describe function!
# That sounds suspicious
<img src="https://media4.giphy.com/media/lxfXcVFaE42By/giphy.gif?cid=6c09b952maa6322c0k5ptstqtnyfh17567xj6xpjyc6nsoae&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=g" width=700 />

In [ ]:
# other descriptors/summary statistics

series_fav_num.describe()

count    3.000000
mean     3.666667
std      3.055050
min      1.000000
25%      2.000000
50%      3.000000
75%      5.000000
max      7.000000
dtype: float64

## Pandas: DataFrame

Remember:
- `Series`:  1d data object
- `DataFrame`: 2d data object

`DataFrame`s represent two-dimensional data, for example, grades:

|           | Quiz 0 | Quiz 1 | Quiz 2 |
|-----------|--------|--------|--------|
| Student 0 | 80     | 90     | 50     |
| Student 1 | 87     | 92     | 80     |

Each column or row above could be considered a `Series` object (as we'll see later, we can indeed extract a single row or column of a dataframe as a `Series` object).

In [ ]:
import pandas as pd
import numpy as np

quiz_array = np.array([[80, 90, 50],
                 [87, 92, 80]])

df_quiz = pd.DataFrame(quiz_array,
                       columns=('quiz0', 'quiz1', 'quiz2'),
                       index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# we construct a dataframe as a dictionary
# keys of the dictionary are columns of dataframe
# values are lists (or tuples) of the values in each column
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
pd.DataFrame(quiz_dict, index=('student0', 'student1'))

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# another way to construct, this time the transpose
quiz_dict2 = {'student0': [80, 90, 50],
             'student1': [87, 92, 80]}
pd.DataFrame(quiz_dict2, index=('quiz0', 'quiz1', 'quiz2'))

student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

In [ ]:
# could also use .transpose() or even .T
df_quiz.transpose()
# df_quiz.T
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# we can also add the column or index names after creation
df_quiz = pd.DataFrame(quiz_array)
df_quiz

0   1   2
0  80  90  50
1  87  92  80

In [ ]:
df_quiz.columns = ['quiz0', 'quiz1', 'quiz2']
df_quiz.index = ('student0', 'student1')
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

### Describing a `pd.DataFrame`

Similar to Series (for now), but with a couple differences:
- `DataFrame.iloc[].idxmin()` or `DataFrame.loc[].idxmin()`
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has smallest value
    - pandas gives the row number, not the index
- `DataFrame.iloc[].idxmax()` or `DataFrame.loc[].idxmax()`
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has largest value
    - pandas gives the row number, not the index
- `DataFrame.mean()`
- `DataFrame.min()`
- `DataFrame.max()`
- `DataFrame.std()`
- `DataFrame.var()`

New to pandas:
- `DataFrame.count()`
    - number of item pairs in series
- `DataFrame.describe()`
    - summary statistics

In [ ]:
# by default, each method applies operation to entire column of data
# note that there may be some complaining from python if not all the columns are numeric
df_quiz.mean()

quiz0    83.5
quiz1    91.0
quiz2    65.0
dtype: float64

In [ ]:
# we can also pass axis parameter to specify if operation should be applied to row or column
# !remember!
# axis=0 -> apply operation across all rows and returns operation output per col
# axis=1 -> apply operation across all cols and returns operation output per row
df_quiz.mean(axis=1)

student0    73.333333
student1    86.333333
dtype: float64

In [ ]:
# describe only works on columns
df_quiz.describe()

quiz0      quiz1      quiz2
count   2.000000   2.000000   2.000000
mean   83.500000  91.000000  65.000000
std     4.949747   1.414214  21.213203
min    80.000000  90.000000  50.000000
25%    81.750000  90.500000  57.500000
50%    83.500000  91.000000  65.000000
75%    85.250000  91.500000  72.500000
max    87.000000  92.000000  80.000000

## Indexing / Accessing a DataFrame
- indexing:
    - `.loc[]` indexing by name of row or column
    - `.iloc[]` indexing by position integer (0, 1, 2, 3, 4 ...)
    & slicing & subsets
- using `:` to get full rows or columns
- single cell's contents: `at`, `iat` & slicing

In [ ]:
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# indexing data by "name"
# remember: rows first, then columns ...
# 1st entry describes which row ('student0')
# 2nd entry describes which col ('quiz0')

df_quiz.loc['student0', 'quiz0']

np.int64(80)

In [ ]:
# index data by position
# 1st entry describes which row.  0 -> the 1st (topmost) row
# 2nd entry describes which col.  2 -> the 3rd (from the left) col
df_quiz.iloc[0, 2]

np.int64(50)

In [ ]:
#In loc, 'quiz0':'quiz2', quiz2 is inclusive
df_quiz.loc['student0','quiz0':'quiz2']

quiz0    80
quiz1    90
quiz2    50
Name: student0, dtype: int64

In [ ]:
#this gives error becuase remember loc, works on the name of the row or column, and since we do not those as the names, it is an error.
df_quiz.loc[0,0:2]

KeyError: 0

In [ ]:
#However, in iloc, 2 is exclusive
df_quiz.iloc[0,0:2]

quiz0    80
quiz1    90
Name: student0, dtype: int64

In [ ]:
# you can use same slicing syntaxes on both .loc and .iloc
# 1st row, last col
df_quiz.iloc[0, -1]

np.int64(50)

In [ ]:
# all rows, only the second col
df_quiz.iloc[:, 1]

student0    90
student1    92
Name: quiz1, dtype: int64

In [ ]:
# all rows, only quiz0
df_quiz.loc[:, 'quiz0']

student0    80
student1    87
Name: quiz0, dtype: int64

In [ ]:
# slicing with named cols and rows
# you can get a range, by name of row/col
# note: this includes both start and stop columns
df_quiz.loc['student0', 'quiz0':'quiz2' ]

quiz0    80
quiz1    90
quiz2    50
Name: student0, dtype: int64

In [ ]:
# watch out:
# when you get ranges indexed by position: include start idx, exclude stop idx)
df_quiz.iloc[0, 0:2 ]

quiz0    80
quiz1    90
Name: student0, dtype: int64

In [ ]:
# if you access directly into dataframe, it will assume you're looking for a column
# (below is equivilent to df_quiz.loc[:, 'quiz0'])
df_quiz['quiz0']

student0    80
student1    87
Name: quiz0, dtype: int64

loc gets rows (and/or columns) with particular labels.

iloc gets rows (and/or columns) at integer locations.

Additionally, `s.loc[0,0:2]`  # rows at index labels between 0 and 1 (inclusive) so this means 0, 1 and 2
`s.iloc[0,0:2]`  # rows at index labels between 0 and 1 (exclusive), so that means 0th and 1st


<img src='https://media1.giphy.com/media/l2R01mSIsazqNQ7ks/giphy.gif?cid=6c09b952x9z29ab4af9xpluk4vjxwzu6tm0nacgw1qxi8e5f&ep=v1_gifs_search&rid=giphy.gif&ct=g' width=700 />

## Modifying a DataFrame
- updating values: single cell
- adding a new column
- `pd.DataFrame.append()` and `pd.DataFrame.concat()`
    - adds a single row to a dataframe
    - `.append()` is deprecated, and may not work depending on your version of Python! Has been replaced with `.concat()` (which we use here)

In [ ]:
# setting single entry in dataframe
df_quiz.loc['student0', 'quiz1'] = 123
df_quiz

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [ ]:
# adding a new column (which student got which grade?)
# notice data frames can include columns of multiple types!
df_quiz['overall grade'] = 'a', 'b'
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50             a
student1     87     92     80             b

In [ ]:
# delete a column
del df_quiz['overall grade']
df_quiz

# There is another way of deleteing a coloumn which is by using the drop() function (Typically much better than the other one)
# df_quiz.drop('overall grade', axis=1)

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [ ]:
# adding a column (next 2 cells) more error robust way of handling indexing
# by explicitly labelling the index we're sure to match more explicitly
s_overgrade = pd.Series({'student1': 'b-',
                         # 'student0': 'a+',
                        'student2': 'f (no quizzes taken)'})
s_overgrade

student1                      b-
student2    f (no quizzes taken)
dtype: object

In [ ]:
# notice how pandas helps us out in aligning our new column with proper row
# (and avoids including student2)
df_quiz['overall grade'] = s_overgrade
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50           NaN
student1     87     92     80            b-

In [ ]:
# how to 'drop' a row (returns a dataframe with row removed)
df_quiz_short = df_quiz.drop('student0')
df_quiz_short

quiz0  quiz1  quiz2 overall grade
student1     87     92     80            b-

In [ ]:
# rebuild df_quiz
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# notice: name of series ends up on index of dataframe
# notice: order of items in series doesnt matter, they're aligned by index
s_student3 = pd.Series({'quiz1': 90,
                        'quiz2': 100,
                        'quiz0': 95},
                      name='student3')
s_student3

quiz1     90
quiz2    100
quiz0     95
Name: student3, dtype: int64

In [ ]:
# add new row to dataframe
pd.concat([df_quiz, s_student3.to_frame().T])

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [ ]:
# also notice: .concat() returns a copy of df_quiz, it isn't modified above
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# thus, must overwrite:
df_quiz = pd.concat([df_quiz, s_student3.to_frame().T])
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [ ]:
# adding a column that is a function of other columns:
df_quiz['average'] = (df_quiz['quiz0'] + df_quiz.quiz1 + df_quiz.quiz2)/3
df_quiz

quiz0  quiz1  quiz2    average
student0     80     90     50  73.333333
student1     87     92     80  86.333333
student3     95     90    100  95.000000

In [ ]:
df_quiz.average

student0    73.333333
student1    86.333333
student3    95.000000
Name: average, dtype: float64

In [ ]:
df_quiz['quiz0']

student0    80
student1    87
student3    95
Name: quiz0, dtype: int64

### Operating on DataFrame & Series Objects

Your operators do what you'd expect them to:

In [ ]:
df_quiz * 1000

quiz0  quiz1   quiz2       average
student0  80000  90000   50000  73333.333333
student1  87000  92000   80000  86333.333333
student3  95000  90000  100000  95000.000000

In [ ]:
# we can also use comparison operators (super helpful, see boolean indexing next)
df_quiz >= 85

quiz0  quiz1  quiz2  average
student0  False   True  False    False
student1   True   True  False     True
student3   True   True   True     True

### Boolean Indexing into DataFrame

Sometimes we want to grab only the rows or columns which meet a particular condition.

"Get all students whose grade was higher than 85 on quiz 1"

In [ ]:
quiz_dict = {'quiz0': [80, 87, 60, 30],
            'quiz1': [90, 92, 60, 23],
            'quiz2': [50, 80, 70, 64]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1', 'student2', 'student3'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student2     60     60     70
student3     30     23     64

In [ ]:
# quiz 2 is a series object which contains every index's quiz 2 grade
# one, verbose way:
s_quiz2 = df_quiz.loc[:, 'quiz2']
s_quiz2

student0    50
student1    80
student2    70
student3    64
Name: quiz2, dtype: int64

In [ ]:
# easier way, but not as convenient for seeing what we're about to do
df_quiz.quiz2

student0    50
student1    80
student2    70
student3    64
Name: quiz2, dtype: int64

In [ ]:
# boolean indexing: using a boolean series as index returns only those entries which are True
# notice that since student0 & student3's quiz1 grade wasn't > 70 they aren't
# included below.
df_quiz.loc[s_quiz2 >= 70, :]

quiz0  quiz1  quiz2
student1     87     92     80
student2     60     60     70

In [ ]:
# we can build more complex conditions using
# & (and operator)
# | (or operator)

# all students who got at least an 80 on quiz1 but scored less than 75 on quiz2
s_bool = (df_quiz.loc[:, 'quiz1'] >= 80) & (df_quiz.quiz2  < 75)
s_bool

student0     True
student1    False
student2    False
student3    False
dtype: bool

In [ ]:
df_quiz.loc[s_bool, :]

quiz0  quiz1  quiz2
student0     80     90     50

# Loading Data into Pandas

Data comes from many places:
- Web Scraping
- Application Program Interface (API)
- SQL
- local file:
    - csv
    - JSON
    - fixed width tables (HTML)
    
### Pandas functions which load data
| Mode | Description
| ------ | :------
| **`read_csv`** | Load comma seperated values data from a file or URL (other delimeters too!)
| **`read_xlsx`** | Read data in xls format (Mircosoft Excel)
| **`read-fwf`** | Read data in fixed-width column format (i.e., no delimiters such as tab-separated txt files)
| **`read_clipboard`** | Version of read_csv that reads data from the clipboard; useful for converting tables from web pages
| **`read_html`** | Read all tables contained in the given HTML document.
| **`read_json`** | Read data from a JSON (JavaScript Object Notation) string representation

## Reading CSV into Pandas
- read_csv
- index_col
- header

In [ ]:
import pandas as pd
# note: file must be in same folder as jupyter notebook
pd.read_csv('day-1dataset.csv')

Restaurant   Latitude   Longitude  \
0                    61Sliders  61.149140 -149.878090   
1         907 Alehouse & Grill  61.148140 -149.863132   
2                  907 Wingman  61.188415 -149.907983   
3                 AK Alchemist  61.218773 -149.882808   
4               Alaska Crepery  61.217756 -149.888169   
..                         ...        ...         ...   
286      Yakishabu Sushi House  61.144031 -149.892769   
287  Yamaya Seafood Restaurant  61.216698 -149.898625   
288               Yogo Delight  61.184160 -149.867577   
289              Zorba's Gyros  61.195857 -149.890254   
290    Serrano's Mexican Grill  61.195468 -149.880141   

                                               Address  \
0                    7920 King St, Anchorage, AK 99518   
1    8001 Old Seward Hwy, Anchorage, AK 99518, Unit...   
2    3505 Spenard Rd, Anchorage, AK 99503, United S...   
3    103 E 4th Ave, Anchorage, AK 99501, United States   
4    319 W 5th Ave, Anchorage, AK 99501, United States   
..                                                 ...   
286  720 W Dimond Blvd, Anchorage, AK 99515, United...   
287  825 W 6th Ave, Anchorage, AK 99501, United States   
288  4007 Old Seward Hwy # 200, Anchorage, AK 99503...   
289  2700 Blueberry Rd, Anchorage, AK 99503, United...   
290  201 E Northern Lights Blvd, Anchorage, AK 9950...   

                         PlaceID  \
0                              -   
1    ChIJsX90-NaZyFYRGJ_WD0iQlaA   
2    ChIJ4-dvWd2XyFYR-dL2s0DiD_0   
3    ChIJt_B88yiWyFYRZQB7I68Jokk   
4    ChIJC6dwVAyXyFYR0ZZMmzzULww   
..                           ...   
286  ChIJMdQzoAOZyFYR1rEIFO_2Wyo   
287  ChIJVVN224C9yFYRmmjSJ1vPVj4   
288  ChIJT0w0d7yXyFYRcCATvyPkT6Y   
289  ChIJI7cNe8WXyFYRuJw8-CPA5f4   
290  ChIJH0A8uciXyFYRQvUedUNWEEU   

                                                   URL  AverageExposure  \
0             /biz/61sliders-anchorage?osq=Restaurants         0.124478   
1    /biz/907-alehouse-and-grill-anchorage?osq=Rest...         0.130601   
2           /biz/907-wingman-anchorage?osq=Restaurants         0.109058   
3          /biz/ak-alchemist-anchorage?osq=Restaurants         0.164824   
4      /biz/alaska-crepery-anchorage-2?osq=Restaurants         0.161754   
..                                                 ...              ...   
286  /biz/yakishabu-sushi-house-anchorage-4?osq=Res...         0.184925   
287  /biz/yamaya-seafood-restaurant-anchorage?osq=R...         0.123558   
288        /biz/yogo-delight-anchorage?osq=Restaurants         0.099800   
289        /biz/zorbas-gyros-anchorage?osq=Restaurants         0.116808   
290  /biz/serranos-mexican-grill-anchorage?osq=Rest...         0.141745   

     Stars    ZIP  Count  ...  HED  Unemployment  HUne  Wealth  HWe  \
0      3.6  99507     22  ...    0           4.7     1   88485    0   
1      3.4  99503     93  ...    0           7.9     1   63338    0   
2      4.1  99508      9  ...    0           6.5     1   65430    0   
3      3.8  99501     58  ...    0           7.2     1   61509    0   
4      4.5  99507     22  ...    0           4.7     1   88485    0   
..     ...    ...    ...  ...  ...           ...   ...     ...  ...   
286    3.9  99515     39  ...    1           4.0     1  106755    1   
287    3.7  99501     58  ...    0           7.2     1   61509    0   
288    4.4  99508      9  ...    0           6.5     1   65430    0   
289    4.4  99518     21  ...    0           3.0     0   84045    0   
290    3.9  99577     13  ...    1           3.5     1  111388    1   

     Attraction  Hotspot  Reviews  \
0             1        0        1   
1             0        1      135   
2             1        1      110   
3             1        1      178   
4             1        1      164   
..          ...      ...      ...   
286           0        0       32   
287           1        1      124   
288           1        0      116   
289           1        1       80   
290           1        0      270   

      

In [ ]:
# look at the first few rows (header)
gtky = pd.read_csv('day-1dataset.csv', index_col='Latitude')
gtky.head()

Restaurant   Longitude  \
Latitude                                      
61.149140             61Sliders -149.878090   
61.148140  907 Alehouse & Grill -149.863132   
61.188415           907 Wingman -149.907983   
61.218773          AK Alchemist -149.882808   
61.217756        Alaska Crepery -149.888169   

                                                     Address  \
Latitude                                                       
61.149140                  7920 King St, Anchorage, AK 99518   
61.148140  8001 Old Seward Hwy, Anchorage, AK 99518, Unit...   
61.188415  3505 Spenard Rd, Anchorage, AK 99503, United S...   
61.218773  103 E 4th Ave, Anchorage, AK 99501, United States   
61.217756  319 W 5th Ave, Anchorage, AK 99501, United States   

                               PlaceID  \
Latitude                                 
61.149140                            -   
61.148140  ChIJsX90-NaZyFYRGJ_WD0iQlaA   
61.188415  ChIJ4-dvWd2XyFYR-dL2s0DiD_0   
61.218773  ChIJt_B88yiWyFYRZQB7I68Jokk   
61.217756  ChIJC6dwVAyXyFYR0ZZMmzzULww   

                                                         URL  AverageExposure  \
Latitude                                                                        
61.149140           /biz/61sliders-anchorage?osq=Restaurants         0.124478   
61.148140  /biz/907-alehouse-and-grill-anchorage?osq=Rest...         0.130601   
61.188415         /biz/907-wingman-anchorage?osq=Restaurants         0.109058   
61.218773        /biz/ak-alchemist-anchorage?osq=Restaurants         0.164824   
61.217756    /biz/alaska-crepery-anchorage-2?osq=Restaurants         0.161754   

           Stars    ZIP  Count  White  ...  HED  Unemployment  HUne  Wealth  \
Latitude                               ...                                    
61.149140    3.6  99507     22  20110  ...    0           4.7     1   88485   
61.148140    3.4  99503     93   6167  ...    0           7.9     1   63338   
61.188415    4.1  99508      9  15722  ...    0           6.5     1   65430   
61.218773    3.8  99501     58   9223  ...    0           7.2     1   61509   
61.217756    4.5  99507     22  20110  ...    0           4.7     1   88485   

           HWe  Attraction  Hotspot  Reviews  \
Latitude                                       
61.149140    0           1        0        1   
61.148140    0           0        1      135   
61.188415    0           1        1      110   
61.218773    0           1        1      178   
61.217756    0           1        1      164   

                                                   Amenities  Amenity_Count  
Latitude                                                                     
61.149140                                             Classy              1  
61.148140  Takes Reservations\nOffers Takeout\nNo Deliver...             22  
61.188415  Offers Delivery\nOffers Takeout\nNo Reservatio...             17  
61.218773  Offers Delivery\nOffers Takeout\nNo Reservatio...              3  
61.217756  Takes Reservations\nOffers Delivery\nOffers Ta...             16  

[5 rows x 37 columns]

In [ ]:
# or the last few (tail)
gtky.tail()

Restaurant   Longitude  \
Latitude                                           
61.144031      Yakishabu Sushi House -149.892769   
61.216698  Yamaya Seafood Restaurant -149.898625   
61.184160               Yogo Delight -149.867577   
61.195857              Zorba's Gyros -149.890254   
61.195468    Serrano's Mexican Grill -149.880141   

                                                     Address  \
Latitude                                                       
61.144031  720 W Dimond Blvd, Anchorage, AK 99515, United...   
61.216698  825 W 6th Ave, Anchorage, AK 99501, United States   
61.184160  4007 Old Seward Hwy # 200, Anchorage, AK 99503...   
61.195857  2700 Blueberry Rd, Anchorage, AK 99503, United...   
61.195468  201 E Northern Lights Blvd, Anchorage, AK 9950...   

                               PlaceID  \
Latitude                                 
61.144031  ChIJMdQzoAOZyFYR1rEIFO_2Wyo   
61.216698  ChIJVVN224C9yFYRmmjSJ1vPVj4   
61.184160  ChIJT0w0d7yXyFYRcCATvyPkT6Y   
61.195857  ChIJI7cNe8WXyFYRuJw8-CPA5f4   
61.195468  ChIJH0A8uciXyFYRQvUedUNWEEU   

                                                         URL  AverageExposure  \
Latitude                                                                        
61.144031  /biz/yakishabu-sushi-house-anchorage-4?osq=Res...         0.184925   
61.216698  /biz/yamaya-seafood-restaurant-anchorage?osq=R...         0.123558   
61.184160        /biz/yogo-delight-anchorage?osq=Restaurants         0.099800   
61.195857        /biz/zorbas-gyros-anchorage?osq=Restaurants         0.116808   
61.195468  /biz/serranos-mexican-grill-anchorage?osq=Rest...         0.141745   

           Stars    ZIP  Count  White  ...  HED  Unemployment  HUne  Wealth  \
Latitude                               ...                                    
61.144031    3.9  99515     39  15252  ...    1           4.0     1  106755   
61.216698    3.7  99501     58   9223  ...    0           7.2     1   61509   
61.184160    4.4  99508      9  15722  ...    0           6.5     1   65430   
61.195857    4.4  99518     21   6234  ...    0           3.0     0   84045   
61.195468    3.9  99577     13  22970  ...    1           3.5     1  111388   

           HWe  Attraction  Hotspot  Reviews  \
Latitude                                       
61.144031    1           0        0       32   
61.216698    0           1        1      124   
61.184160    0           1        0      116   
61.195857    0           1        1       80   
61.195468    1           1        0      270   

                                                   Amenities  Amenity_Count  
Latitude                                                                     
61.144031  Offers Delivery\nOffers Takeout\nCasual, Trend...              9  
61.216698  Takes Reservations\nOffers Takeout\nNo Deliver...             15  
61.184160  Offers Takeout\nNo Reservations\nNo Delivery\n...             18  
61.195857  Offers Takeout\nNo Reservations\nAccepts Credi...             11  
61.195468  Offers Delivery\nOffers Takeout\nNo Reservatio...             20  

[5 rows x 37 columns]

In [ ]:
# look at stats for the different classes
class_gtky = gtky.groupby("ZIP")
class_gtky.describe()

Longitude                                                            \
          count        mean       std         min         25%         50%   
ZIP                                                                         
99501      56.0 -148.742000  8.439060 -149.982134 -149.896281 -149.888814   
99502       6.0 -149.916733  0.045542 -149.983585 -149.943912 -149.912612   
99503      94.0 -149.874413  0.058371 -149.952618 -149.904025 -149.885408   
99504      10.0 -149.618327  0.699157 -149.915430 -149.890578 -149.836955   
99507      23.0 -149.867175  0.043462 -149.913815 -149.893826 -149.885075   
99508       9.0 -149.851966  0.054903 -149.907983 -149.890611 -149.867577   
99515      39.0 -149.843831  0.090286 -149.915729 -149.893782 -149.874919   
99517      15.0 -149.865809  0.090081 -149.937970 -149.915144 -149.892066   
99518      21.0 -149.876652  0.074823 -149.942590 -149.897319 -149.890254   
99540       4.0 -149.694135  0.216026 -149.893939 -149.874339 -149.692308   
99577      14.0 -147.550504  8.720974 -149.982857 -149.892293 -149.873930   

                              AverageExposure            ... Reviews          \
              75%         max           count      mean  ...     75%     max   
ZIP                                                      ...                   
99501 -149.872529  -86.719709            56.0  0.153591  ...  230.25  2480.0   
99502 -149.882729 -149.864476             6.0  0.115208  ...   70.00   155.0   
99503 -149.868873 -149.563550            94.0  0.133839  ...  162.75  2967.0   
99504 -149.766768 -147.636225            10.0  0.122940  ...  126.50   414.0   
99507 -149.857953 -149.741059            23.0  0.105630  ...  198.00   426.0   
99508 -149.839750 -149.734193             9.0  0.118777  ...  167.00   226.0   
99515 -149.836392 -149.568249            39.0  0.110079  ...  135.50   607.0   
99517 -149.861268 -149.570695            15.0  0.128230  ...  160.00   486.0   
99518 -149.867133 -149.569488            21.0  0.121858  ...  141.00   358.0   
99540 -149.512104 -149.497986             4.0  0.203595  ...   84.75   102.0   
99577 -149.843747 -117.250918            14.0  0.103617  ...  190.00   270.0   

      Amenity_Count                                                       
              count       mean       std   min    25%   50%    75%   max  
ZIP                                                                       
99501          56.0   8.285714  7.300596   2.0   3.00   4.0  14.25  27.0  
99502           6.0  14.333333  3.983298  11.0  11.25  13.0  16.25  21.0  
99503          94.0  13.361702  7.029662   0.0   9.00  14.0  17.00  31.0  
99504          10.0  12.900000  7.125073   2.0   7.25  13.5  16.75  25.0  
99507          23.0   6.434783  7.011848   0.0   2.00   4.0   8.50  23.0  
99508           9.0  17.444444  6.710274   3.0  17.00  18.0  19.00  29.0  
99515          39.0  12.435897  6.443254   0.0   8.00  14.0  16.00  32.0  
99517          15.0  13.466667  5.755329   3.0  10.00  14.0  17.50  24.0  
99518          21.0  15.380952  5.074211   5.0  12.00  16.0  19.00  27.0  
99540           4.0  16.000000  4.320494  10.0  14.50  17.0  18.50  20.0  
99577          14.0  14.500000  6.560371   2.0  11.50  15.5  18.75  25.0  

[11 rows x 248 columns]

## Saving a DataFrame as a csv
- .to_csv()
- index=False
- header=False
- appending to csv (mode='a', header=None)

In [ ]:
# doesn't save index into first column of csv
gtky.to_csv('gtky_copy.csv', index=False)

In [ ]:
# doesn't save header into first row of csv
gtky.to_csv('gtky_copy_no_head.csv', header=False)

In [ ]:
# why would you want to not save the header?
# you could append to an existing csv with mode = 'a'

gtky.to_csv('gtky_copy2.csv', index=False)
for _ in range(10):
    gtky.to_csv('gtky_copy2.csv', header=False, mode='a')

# Basic tools in preparation for APIs

The `requests` module comes into play soon. While you may have installed it in the terminal earlier, it is actually a [magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip) command, which means it can be installed directly from jupyter (should you ever need to install it again, or if you had difficulty installing it earlier).

In [ ]:
!pip3 install requests --break-system-packages

#or

#pip3 install requests

#or

#pip install requests


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3.13 -m pip install --upgrade pip


## Building a DataFrame row by row

We often get data in chunks (web scraping / API calls).  We'll need to store our data incrementally:


In [ ]:
import pandas as pd

dict_list = [{'a': 1, 'b': 2, 'c': 3},
             {'a': 4, 'b': 3874, 'c': 398}]

df = pd.DataFrame()
print(df)
for d in dict_list:
    df = pd.concat([df, pd.Series(d).to_frame().T])

df

Empty DataFrame
Columns: []
Index: []


a     b    c
0  1     2    3
0  4  3874  398

In [ ]:
# to include index names
list_dict = [{'a': 1, 'b': 2, 'c': 3},
            {'a': 4, 'b': 3874, 'c': 398}]

name_list = ['first', 'second']

df = pd.DataFrame()
print(df)
for idx in range(2):
    # extract dictionary & name
    d = list_dict[idx]
    name = name_list[idx]

    # build series and name it
    series = pd.Series(d, name=name)

    df = pd.concat([df, series.to_frame().T])

df

Empty DataFrame
Columns: []
Index: []


a     b    c
first   1     2    3
second  4  3874  398

# Timestamps

Many datasets include a timestamp, or include a date/time as a feature in the dataset. Understanding how to deal with these can be important! It is important to understand how to handle such timestamp and what are the functions that can help us. We'll look a few time highlights which will come in handy on Homework 2.

## Unix Time

- [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) Coordinated Universal Time
    - time zone at 0 deg longitude
        - how is 0 deg longitude defined?  
            - A succesfully warring empire (United Kingdom) chose it
                - (It would be convenient if a metric system loving empire had been more successful at war ...)
- [Unix Time](https://en.wikipedia.org/wiki/Unix_time) is The number of seconds which have passed since 00:00:00 UTC on 1 Jan 1970 (ignoring leap seconds)
![unix](https://i.redd.it/o1li4ktbyf871.png)
- UTC is time zone agnostic
    - (more on this next lesson...)

## Python's `datetime`, `timedelta`, and pytz
- helpful for all those pesky unit conversions

In [1]:
from datetime import datetime, timedelta

# would you believe that the below is exactly 2 am on Valentine's Day 2021?
utc_example = 1726256326
utc_example1=1726256325
utc_example1=utc_example1-utc_example

# assumes the time zone of the machine its running on!
dt0 = datetime.fromtimestamp(utc_example1)
dt0

datetime.datetime(1969, 12, 31, 23, 59, 59)

In [ ]:
date1 + timedelta(days = 90)

datetime.datetime(1900, 4, 25, 0, 0)

In [ ]:
str1 = "September 25"
str2 = "10 am"
newdate = datetime.strptime(str1 + ' ' + str2, '%B %d %H %p')
newdate

/var/folders/rf/b4q1n_7s0bl3g8s3ww6qx_mr0000gn/T/ipykernel_1470/203930150.py:3: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
  newdate = datetime.strptime(str1 + ' ' + str2, '%B %d %H %p')


datetime.datetime(1900, 9, 25, 10, 0)

In [ ]:
newnewdate = datetime(year = 2023, month = newdate.month, day = newdate.day, hour = newdate.hour)
newnewdate

datetime.datetime(2023, 9, 25, 10, 0)

In [ ]:
import pytz
tz_mali = pytz.timezone("Africa/Timbuktu")
inmali = tz_mali.localize(newnewdate)

In [ ]:
tz_est = pytz.timezone("EST")
inmali.astimezone(tz_est)

datetime.datetime(2023, 9, 25, 5, 0, tzinfo=<DstTzInfo 'EST' EST-1 day, 19:00:00 STD>)

In [ ]:
# what about right.... now?
dt1 = datetime.now()
dt1

datetime.datetime(2025, 1, 12, 12, 41, 8, 169325)

In [ ]:
# we can set future dates as well
dt2 = datetime(year=2031, month=4, day=15, hour=9, minute=26, second=53)
dt2

datetime.datetime(2031, 4, 15, 9, 26, 53)

In [ ]:
# we can access meaningful date attributes of a datetime object
# year, month, day, hour, minute, second
dt2.month, dt2.day

(4, 15)

In [ ]:
# we can add / subtract timedelta objects
offset = timedelta(days=5, seconds=8979)

print(dt2)
print(dt2 + offset)

2031-04-15 09:26:53
2031-04-20 11:56:32


In [11]:
# use strftime to cast a time to a string that contains other words
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
s = datetime.now().strftime('the time is now: %B-%d-%Y %H:%M %p')
s

'the time is now: January-13-2025 16:16 PM'

%B: The full month name (e.g., "September").

%d: The day of the month as a zero-padded decimal number (e.g., "30").

%Y: The year with century as a decimal number (e.g., "2024").

%H: The hour (00-23) as a zero-padded decimal number (e.g., "21" for 9 PM in 24-hour format).

or

%I if you want it in military time

%M: The minute as a zero-padded decimal number (e.g., "20").

%p: AM or PM (e.g., "PM").


Python processes the string according to the format specifiers and stores it in an internal datetime object. Internally, the datetime object doesn't store the data in the order it was originally written (i.e., month, day, year), but rather in the canonical order of year, month, day.

In [13]:
# use strptime to take the time from strings contain other words
datetime.strptime('the time is now: September-30-2024 9:20 PM', 'the time is now: %B-%d-%Y %H:%M %p')

datetime.datetime(2024, 9, 30, 9, 20)

In [ ]:
# you can save useful time info in a dictionary (which could then become a series -> data frame)
dt = datetime.now()
{'hour': dt.hour,
'minute': dt.minute}

{'hour': 12, 'minute': 42}

In [ ]:
# you can figure out how old you are in seconds
mohit_age = (datetime.now() - datetime(year=1995, month=2, day=10, hour=10, minute=00)).total_seconds()
print(mohit_age)
# put it in billions (it wasn't too long ago that I turned 1 billion!)
mohit_age/ 1e09

944275391.717549


0.9442753917175489

# API
###  Definitions
**API** Application Program Interface
 - a server which gives out data (often over the internet)
 - note: 'API', in general, refers to the barrier between two pieces of software:
     - in this case, the server which hosts data & our own software which requests it

![apii](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F65472b4e-8deb-474d-82e7-6ca5632b3556_505x529.png)


 **JSON** JavaScript Object Notation
  - a method of storing objects as text
  - much like the nested dictionaries ... JSON and similar formats are often trees

![json](https://project-static-assets.s3.amazonaws.com/APISpreadsheets/APIMemes/WhoIsJason.jpeg)


## OpenWeather API
What information does this offer?

[https://openweathermap.org/api](https://openweathermap.org/api)

How do I get ready to use it?
- sign up for an account
    - [https://home.openweathermap.org/users/sign_up](https://home.openweathermap.org/users/sign_up)
- get an api key (my key was emailed to me with my confirmation of account)
    - [https://home.openweathermap.org/api_keys](https://home.openweathermap.org/api_keys)

![ap](https://www.memecreator.org/static/images/memes/4593014.jpg)
        
Think of APIs as a hybrid of a website and a function.  Its a website where your query is stored in the address:
    
    https://api.openweathermap.org/data/3.0/onecall?lat=42.3601&lon=-71.0589&appid=YOUR-API-KEY-HERE-THIS-WONT-WORK&units=imperial
    
The result is a JSON object, which we can quickly convert to our dictionary of dictionary tree format.

In [ ]:
api_key = 'cf758020c3c57082bbfd8b62d88ca683'

# north = positive, south = negative
lat = 42.3601
# west = positive, east = negative
lon = -71.0589

units = 'imperial'
url = f'https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={api_key}&units={units}'

print(url)

https://api.openweathermap.org/data/3.0/onecall?lat=42.3601&lon=-71.0589&appid=cf758020c3c57082bbfd8b62d88ca683&units=imperial


In [ ]:
import requests

# get url as a string
url_text = requests.get(url).text
url_text

'{"lat":42.3601,"lon":-71.0589,"timezone":"America/New_York","timezone_offset":-18000,"current":{"dt":1736703957,"sunrise":1736683910,"sunset":1736717581,"temp":34.29,"feels_like":27.59,"pressure":1014,"humidity":58,"dew_point":22.3,"uvi":1.24,"clouds":20,"visibility":10000,"wind_speed":8.05,"wind_deg":320,"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"rain":{"1h":0.59}},"minutely":[{"dt":1736703960,"precipitation":0},{"dt":1736704020,"precipitation":0},{"dt":1736704080,"precipitation":0},{"dt":1736704140,"precipitation":0},{"dt":1736704200,"precipitation":0},{"dt":1736704260,"precipitation":0},{"dt":1736704320,"precipitation":0},{"dt":1736704380,"precipitation":0},{"dt":1736704440,"precipitation":0},{"dt":1736704500,"precipitation":0},{"dt":1736704560,"precipitation":0},{"dt":1736704620,"precipitation":0},{"dt":1736704680,"precipitation":0},{"dt":1736704740,"precipitation":0},{"dt":1736704800,"precipitation":0},{"dt":1736704860,"precipitation":0},{"dt":1

In [ ]:
# should not have to install the below
import json

# convert json to a nested dict
weather_dict = json.loads(url_text)

weather_dict.keys()
weather_dict['hourly']

weather_dict['hourly'][4]['clouds']
for i in range(10):
    print(weather_dict['hourly'][i]['clouds'])


17
20
17
14
11
9
8
9
5
7


In [ ]:
#what does one hour of weather look like
weather_dict['hourly'][2]

{'dt': 1736708400,
 'temp': 34.23,
 'feels_like': 31.59,
 'pressure': 1014,
 'humidity': 59,
 'dew_point': 22.62,
 'uvi': 0.77,
 'clouds': 17,
 'visibility': 10000,
 'wind_speed': 3.2,
 'wind_deg': 302,
 'wind_gust': 7.67,
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'pop': 0}

## Cleaning up data from one hour

In [ ]:
from datetime import datetime
import pandas as pd

hour_dict = weather_dict['hourly'][0]
print(hour_dict)

# lets convert from unix time to a datetime (easier to use)
hour_dict['datetime'] = datetime.fromtimestamp(hour_dict['dt'])

pd.Series(hour_dict)

{'dt': 1736701200, 'temp': 33.85, 'feels_like': 29.53, 'pressure': 1014, 'humidity': 59, 'dew_point': 22.3, 'uvi': 1.55, 'clouds': 17, 'visibility': 10000, 'wind_speed': 4.7, 'wind_deg': 318, 'wind_gust': 7.27, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'pop': 0, 'datetime': datetime.datetime(2025, 1, 12, 12, 0)}


dt                                                   1736701200
temp                                                      33.85
feels_like                                                29.53
pressure                                                   1014
humidity                                                     59
dew_point                                                  22.3
uvi                                                        1.55
clouds                                                       17
visibility                                                10000
wind_speed                                                  4.7
wind_deg                                                    318
wind_gust                                                  7.27
weather       [{'id': 801, 'main': 'Clouds', 'description': ...
pop                                                           0
datetime                                    2025-01-12 12:00:00
dtype: object

In [ ]:
df_hourly = pd.DataFrame()
for hour_dict in weather_dict['hourly']:

    # lets convert from unix time to a datetime (easier to use)
    hour_dict['datetime'] = datetime.fromtimestamp(hour_dict['dt'])

    s_hour = pd.Series(hour_dict)

    df_hourly = pd.concat([df_hourly, s_hour.to_frame().T], ignore_index=True)

df_hourly.head()

dt   temp feels_like pressure humidity dew_point   uvi clouds  \
0  1736701200  33.85      29.53     1014       59      22.3  1.55     17   
1  1736704800  34.29       31.1     1014       58      22.3  1.24     20   
2  1736708400  34.23      31.59     1014       59     22.62  0.77     17   
3  1736712000  34.11      34.11     1014       62     23.56  0.34     14   
4  1736715600  32.56      32.56     1014       70      24.8     0     11   

  visibility wind_speed wind_deg wind_gust  \
0      10000        4.7      318      7.27   
1      10000       3.65      310      6.73   
2      10000        3.2      302      7.67   
3      10000        1.1      270      3.29   
4      10000       1.05      185      1.12   

                                             weather pop             datetime  
0  [{'id': 801, 'main': 'Clouds', 'description': ...   0  2025-01-12 12:00:00  
1  [{'id': 801, 'main': 'Clouds', 'description': ...   0  2025-01-12 13:00:00  
2  [{'id': 801, 'main': 'Clouds', 'description': ...   0  2025-01-12 14:00:00  
3  [{'id': 801, 'main': 'Clouds', 'description': ...   0  2025-01-12 15:00:00  
4  [{'id': 801, 'main': 'Clouds', 'description': ...   0  2025-01-12 16:00:00

## Lecture Break/Practice 3

La Chaux-de-Fonds, Switzerland is located at:

    47.101333° N, 6.825° E
    
1. Create a dataframe of the next 48 hours of their weather as was done above
2. (++) Make a function `get_forecast` which accepts:
    - `lat`
    - `lon`
    - `api_key`
    - `units` (default = 'imperial')
    
    and returns a dataframe of the next 48 hours of the location's weather. Test it on a location of your choice.

## Looking Ahead; Spotify (for use on Homework 2)

![spot](https://static1.srcdn.com/wordpress/wp-content/uploads/2021/12/Spotify-Wrapped-Memes-Featured.jpeg)

The Spotify API is quite powerful and gives us access to any song/artist in its libraries, plus even more information that you might not have thought of. There is also a module that has been created to access the API within python. Open up a terminal (or do it in jupyter notebook; this is a magic module) and run:

`pip install spotipy`

[SPOTIPY LINK](https://spotipy.readthedocs.io/en/2.25.0/)

In [ ]:
!pip3 install spotipy --break-system-packages


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3.13 -m pip install --upgrade pip


In [ ]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

Just like with OpenWeather, we need to make an account [here](https://developer.spotify.com/) (this is essentially the same as making a regular Spotify account) and then get an API key (Spotify requires two things, actually, a Client ID and a secret key). At the above website, go to:

- Dashboard
- Log into your Spotify account (make one if you don't have one)
- Accept the terms of using the API
- Create an app (you can call it anything, I called mine `DS3000_Spotify`)
- Get a client ID (mine is `952bb78187fd483b9a9e1edc7ab78100`, though it is usually good practice to **not** share this) and a client secret (**never share this with anyone**)

In [ ]:
# Authentication
cid = '952bb78187fd483b9a9e1edc7ab78100'
cid_secret='[YOUR CLIENT SECRET]'
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=cid_secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

You will learn more about how to use Spotipy, including the tricky bits that are unique to its usage, on Homework 2. **START THIS EARLY ONCE IT IS RELEASED THIS WEEK!!**